#!/usr/bin/env node
// ============================================================
// kb-summary.js — Knowledge Base Summary Generator
// Reads kb/project-state.json and kb/event-log.jsonl,
// then writes docs/core-rules/PROJECT_STATE.md
// as a human+agent-readable summary.
//
// Usage: node kb-summary.js
// ============================================================

import fs   from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const STATE_PATH    = path.join(__dirname, 'kb', 'project-state.json')
const EVENT_PATH    = path.join(__dirname, 'kb', 'event-log.jsonl')
const OUTPUT_PATH   = path.join(__dirname, 'docs', 'core-rules', 'PROJECT_STATE.md')

function loadState() {
  if (!fs.existsSync(STATE_PATH)) {
    console.error('[kb-summary] kb/project-state.json not found. Run npm run scan:export first.')
    process.exit(1)
  }
  return JSON.parse(fs.readFileSync(STATE_PATH, 'utf-8'))
}

function loadRecentEvents(days = 7) {
  if (!fs.existsSync(EVENT_PATH)) return []
  const since = new Date(Date.now() - days * 24 * 60 * 60 * 1000)
  return fs.readFileSync(EVENT_PATH, 'utf-8')
    .split('\n')
    .filter(Boolean)
    .map(line => { try { return JSON.parse(line) } catch { return null } })
    .filter(e => e && new Date(e.ts) >= since)
    .slice(-20)
}

function trendArrow(delta) {
  if (delta < 0) return `↓ ${Math.abs(delta)} (improving)`
  if (delta > 0) return `↑ ${delta} (degrading)`
  return 'unchanged'
}

function topRiskFiles(files, n = 3) {
  return Object.entries(files)
    .sort(([, a], [, b]) => b.riskScore - a.riskScore)
    .slice(0, n)
}

function generateMarkdown(state, events) {
  const h = state.currentHealth
  const ts = new Date(state.meta.generatedAt).toISOString()
  const topFiles = topRiskFiles(state.files)

  // Recent events summary
  const scanEvents  = events.filter(e => e.event === 'scan')
  const fixEvents   = events.filter(e => e.event === 'fix')
  const blockEvents = events.filter(e => e.event === 'gate_block')
  const bypassEvents = events.filter(e => e.event === 'bypass')

  // Compliance exposure summary
  const compLines = Object.entries(state.complianceExposure)
    .filter(([, d]) => d.openViolations > 0)
    .sort(([, a], [, b]) => b.openViolations - a.openViolations)
    .map(([k, d]) => `- **${k}**: ${d.openViolations} open violation${d.openViolations > 1 ? 's' : ''} (rules: ${d.violatingRules.join(', ')})`)
    .join('\n')

  return `# Project State

> **Knowledge Layer: 0 — Always loaded.**
> Auto-generated from kb/project-state.json — do not edit manually.
> Last updated: ${ts}

---

## Current Health

| Metric | Value |
|---|---|
| Total violations | **${h.totalViolations}** (${trendArrow(h.trendDelta)}) |
| Critical | ${h.bySeverity.CRITICAL} |
| High | ${h.bySeverity.HIGH} |
| Medium | ${h.bySeverity.MEDIUM} |
| Low | ${h.bySeverity.LOW} |
| Risk score | ${h.riskScore}/100 |
| Trend | ${h.trend} |
| Gate 1 | ${h.gate1Status} |
| Gate 2 | ${h.gate2Status} |
| Unused deps | ${state.dependencies.unused.length} (${state.dependencies.totalBloatKb} kB bloat) |

---

## Highest Risk Files

${topFiles.map(([file, d]) => `**${file}** — riskScore: ${d.riskScore}/100
- Violations: ${d.violations.length}
- Compliance at risk: ${d.complianceAtRisk.length > 0 ? d.complianceAtRisk.join(', ') : 'none mapped'}`).join('\n\n')}

---

## Compliance Exposure

${compLines || '- No compliance violations detected'}

---

## Recent Events (last 7 days)

${events.length === 0 ? '- No events recorded' : events.slice(-8).reverse().map(e => {
    const date = new Date(e.ts).toISOString().split('T')[0]
    if (e.event === 'scan')       return `- ${date}: Scan — ${e.total} violations (${e.critical} CRITICAL) — Gate 1: ${e.gate1}`
    if (e.event === 'fix')        return `- ${date}: Fix applied — ${e.ruleId} in ${e.file} by ${e.by}`
    if (e.event === 'gate_block') return `- ${date}: GATE ${e.gate} BLOCKED — ${e.reason}`
    if (e.event === 'bypass')     return `- ${date}: BYPASS detected — ${e.method} by ${e.by}`
    return `- ${date}: ${e.event}`
  }).join('\n')}

---

## Open Questions for TRAE

${h.gate1Status === 'BLOCKED'
  ? `- Gate 1 is BLOCKED — ${h.bySeverity.CRITICAL} CRITICAL and ${h.bySeverity.HIGH} HIGH violations must be resolved before committing.`
  : '- Gate 1 is PASSED — no blocking violations.'}
${bypassEvents.length > 0
  ? `- ${bypassEvents.length} bypass event(s) detected in the last 7 days — review event-log.jsonl for details.`
  : ''}

---

*Generated by kb-summary.js from kb/project-state.json*
*To update: npm run knowledge:update*
`
}

const state  = loadState()
const events = loadRecentEvents(7)
const md     = generateMarkdown(state, events)

fs.writeFileSync(OUTPUT_PATH, md, 'utf-8')
console.log(`[kb-summary] PROJECT_STATE.md written to docs/core-rules/`)
console.log(`[kb-summary] ${state.currentHealth.totalViolations} violations | ${Object.keys(state.files).length} files | ${Object.keys(state.complianceExposure).length} compliance standards`)
