// ============================================================
// KnowledgeGraphView.jsx — Renders the AI Knowledge Graph
// Demonstrates the relationships between files, violations,
// rules, and compliance standards using Force Directed Graph.
// ============================================================

import { useEffect, useState, useRef } from 'react'
import ForceGraph2D from 'react-force-graph-2d'

export default function KnowledgeGraphView({ width, height }) {
  const [graphData, setGraphData] = useState({ nodes: [], links: [] })
  const fgRef = useRef()

  useEffect(() => {
    // Fetch the knowledge graph generated by graph-builder.js
    fetch('/knowledge-graph.json?t=' + Date.now())
      .then(res => res.json())
      .then(data => {
        // Transform to force-graph format: { nodes, links: [{source, target}] }
        const nodesArray = Array.isArray(data.nodes) ? data.nodes : Object.values(data.nodes)
        const nodes = nodesArray.map(n => ({
          id: n.id,
          name: n.name || n.id,
          group: n.type,
          // Make important nodes visually larger
          val: n.type === 'standard' ? 4 : n.type === 'file' ? 3 : n.type === 'rule' ? 2 : 1
        }))

        const links = data.edges
          .filter(e => nodesArray.find(n => n.id === e.from) && nodesArray.find(n => n.id === e.to))
          .map(e => ({
            source: e.from,
            target: e.to,
            label: e.relation
          }))

        setGraphData({ nodes, links })
      })
      .catch(err => console.error("Failed to load knowledge graph", err))
  }, [])

  const getNodeColor = (node) => {
    switch (node.group) {
      case 'file': return '#94a3b8'       // Slate (Neutral)
      case 'violation': return '#ef4444'  // Red (Danger)
      case 'rule': return '#f59e0b'       // Amber (Warning)
      case 'standard': return '#10b981'   // Emerald (Success)
      case 'dependency': return '#3b82f6' // Blue (Info)
      default: return '#6366f1'           // Indigo
    }
  }

  return (
    <div style={{ 
      background: '#0f172a', 
      borderRadius: '0.75rem', 
      overflow: 'hidden', 
      border: '1px solid #1e293b',
      boxShadow: 'inset 0 2px 10px rgba(0,0,0,0.5)',
      width: '100%',
      height: '100%'
    }}>
      {graphData.nodes.length > 0 ? (
        <ForceGraph2D
          ref={fgRef}
          width={width}
          height={height}
          graphData={graphData}
          nodeColor={getNodeColor}
          nodeLabel="name"
          nodeRelSize={4}
          linkColor={() => 'rgba(148, 163, 184, 0.15)'}
          linkWidth={1}
          d3VelocityDecay={0.4}
          onNodeClick={(node) => {
            if (fgRef.current) {
              fgRef.current.centerAt(node.x, node.y, 1000)
              fgRef.current.zoom(3, 1000)
            }
          }}
          // Auto-fit to screen after initial render
          onEngineStop={() => fgRef.current && fgRef.current.zoomToFit(400, 20)}
        />
      ) : (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: '#64748b' }}>
          Loading Knowledge Graph...
        </div>
      )}
    </div>
  )
}
