// ============================================================
// useScannerData — Custom React Hook
// Fetches scan-report.json (generated by scanner-output.js)
// and returns the structured scan data for the Dashboard.
//
// States: idle → loading → ready | error
// Auto-refreshes every 30 seconds if the tab is visible.
//
// Data source detection:
//   - CLI server (devops-guard dashboard): /api/scan-report.json
//   - Vite dev server:                     /scan-report.json
// ============================================================

import { useState, useEffect, useCallback } from 'react'

/**
 * Detects whether we're running inside the CLI-embedded server
 * by looking at the presence of a known header or falling back
 * to the first successful response.
 */
function getReportUrl() {
  // When served by the CLI server, data lives under /api/
  // When served by Vite dev, publicDir serves it at root /
  // We try /api/ first; if 404, fall back to /
  return '/api/scan-report.json'
}

const FALLBACK_URL     = '/scan-report.json'
const REFRESH_INTERVAL = 30_000 // 30 seconds

export function useScannerData() {
  const [data,      setData]      = useState(null)
  const [status,    setStatus]    = useState('idle')   // 'idle' | 'loading' | 'ready' | 'error'
  const [lastFetch, setLastFetch] = useState(null)
  const [error,     setError]     = useState(null)
  const [baseUrl,   setBaseUrl]   = useState(null)

  const fetchReport = useCallback(async () => {
    setStatus('loading')

    // Resolve the correct base URL on first call
    const urls = baseUrl
      ? [baseUrl]
      : [getReportUrl(), FALLBACK_URL]

    let lastErr = null
    for (const url of urls) {
      try {
        const res = await fetch(`${url}?t=${Date.now()}`)
        if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`)
        const json = await res.json()
        setData(json)
        setLastFetch(new Date())
        setError(null)
        setStatus('ready')
        // Remember which URL worked
        if (!baseUrl) setBaseUrl(url)
        return
      } catch (err) {
        lastErr = err
      }
    }

    // All URLs failed
    setError(lastErr?.message ?? 'Failed to fetch report')
    setStatus('error')
  }, [baseUrl])

  // Initial fetch
  useEffect(() => {
    fetchReport()
  }, [fetchReport])

  // Auto-refresh when tab becomes visible or on interval
  useEffect(() => {
    const onVisible = () => {
      if (document.visibilityState === 'visible') fetchReport()
    }
    document.addEventListener('visibilitychange', onVisible)

    const timer = setInterval(fetchReport, REFRESH_INTERVAL)
    return () => {
      document.removeEventListener('visibilitychange', onVisible)
      clearInterval(timer)
    }
  }, [fetchReport])

  // ─── Derived metrics ──────────────────────────────────────
  const metrics = data ? {
    criticalCount:   data.summary.bySeverity.CRITICAL || 0,
    highCount:       data.summary.bySeverity.HIGH     || 0,
    mediumCount:     data.summary.bySeverity.MEDIUM   || 0,
    lowCount:        data.summary.bySeverity.LOW       || 0,
    totalViolations: data.summary.totalSecurityViolations,
    unusedDeps:      data.summary.unusedDependencies,
    bloatKb:         data.summary.totalBloatKb,
    timeSaved:       data.summary.timeSavedPerCommitMin,
    gate1Status:     data.summary.gate1Status,
    gate2Status:     data.summary.gate2Status,
    scannedFiles:    data.summary.srcFilesScanned,
    rulesLoaded:     data.meta.rulesLoaded,
    scanMs:          data.meta.scanDurationMs,
    generatedAt:     data.meta.generatedAt,
  } : null

  return {
    data,
    metrics,
    status,
    error,
    lastFetch,
    refresh: fetchReport,
    isLoading: status === 'loading',
    isReady:   status === 'ready',
    hasError:  status === 'error',
  }
}
